version: '2'
services:
  books_db:
      image: postgres
      container_name: "books_db"
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./db:/var/lib/postgresql/data
        - ./scripts/db.sql:/docker-entrypoint-initdb.d/create_tables.sql
      ports:
        - "5432:5432"

  books_server:
    build: .
    working_dir: /usr/src/app
    command: dist/main.js
    restart: always
    ports:
      - "3000:3000"
      
    depends_on: 
     - books_db

 